platform :ios, '8.0'

target 'BAFluidView' do
  use_frameworks!

  pod "BAFluidView", :path => "../"

  target 'BAFluidView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
